<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Airline Tweets Sentiment Analysis Lab

_Authors: Phillippa Thomson (NYC)_

---

You are going to be analyzing tweets about airlines.  These have been hand-tagged with sentiment.  There are three categories: positive, neutral, and negative.

Use VADER to calculate sentiment for each tweet, and see if you can correctly predict the hand-tagged sentiment.

What is the accuracy?  Print out a heatmap to see where your model performs well, and where it performs poorly.

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
tweets = pd.read_csv("../data/Tweets.csv",encoding = "ISO-8859-1")
tweets.head()

,airline_sentiment,airline,text
0,neutral,Virgin America,@VirginAmerica What @dhepburn said.
1,positive,Virgin America,@VirginAmerica plus you've added commercials t...
2,neutral,Virgin America,@VirginAmerica I didn't today... Must mean I n...
3,negative,Virgin America,@VirginAmerica it's really aggressive to blast...
4,negative,Virgin America,@VirginAmerica and it's a really big bad thing...

### 1. Preview the airline_sentiment column.
- What percentage of reviews are positive, neutral, and negative?

### 2. Load in the Sentiment IntensityAnalyzer from Vader and add compound, negative, neutral, and positive scores into the DataFrame.

In [5]:
# you may need to install vaderSentiment first
# pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

In [24]:
tweets['text'][0]

'@VirginAmerica What @dhepburn said.'

In [6]:
example = sia.polarity_scores(tweets['text'][0])
example

{'compound': 0.0, 'neg': 0.0, 'neu': 1.0, 'pos': 0.0}

In [22]:
# acomplete this function
def unload_dict(df):
    polarity = sia.polarity_scores(df['text'])
    df['compound'] = 
    df['neg'] = 
    df['neu'] = 
    df['pos'] = 
    return df

In [23]:
#apply unload dict to df
tweets.head()

,airline_sentiment,airline,text,compound,neg,neu,pos
0,neutral,Virgin America,@VirginAmerica What @dhepburn said.,0.0000,0.000,1.000,0.0
1,positive,Virgin America,@VirginAmerica plus you've added commercials t...,0.0000,0.000,1.000,0.0
2,neutral,Virgin America,@VirginAmerica I didn't today... Must mean I n...,0.0000,0.000,1.000,0.0
3,negative,Virgin America,@VirginAmerica it's really aggressive to blast...,-0.5984,0.246,0.754,0.0
4,negative,Virgin America,@VirginAmerica and it's a really big bad thing...,-0.5829,0.321,0.679,0.0

### 3. Store airline_sentiment in y to use as labels and create an appropriate feature matrix, X.

In [ ]:
# A:

### 4. Fit a model of your choice to predict airline_sentient and cross-validate.

In [ ]:
# A:

In [ ]:
# A:

In [ ]:
# A:

In [ ]:
# A:

### 5. Display the confusion matrix.
- What reviews are difficult to identify?

In [ ]:
# A:

### 6. Print the classification report and discuss the characteristics of the model.

In [ ]:
# A:

The model does ok with negative tweets (the predominant class) but quite poorly with neutral.

To put this in perspective, human concordance, the probability that two people assign the same sentiment to an observation is usually around 70%-80% our baseline is at 63%. Even small increases in accuracy quickly move us towards a theoretical maximum in performance.